name: oxy
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0
dependencies:
  uuid: ^4.0.0
  shared_preferences: ^2.0.0
  intl: 0.20.2
  supabase_flutter: '>=1.10.0'
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  go_router: ^16.2.0
  provider: any
  pdf: ^3.10.0
  printing: ^5.12.0
  path_provider: ^2.1.0
  share_plus: ^7.2.0
  image_picker: ^1.0.0
  hugeicons: ^0.0.7
  geolocator: ^12.0.0
  geocoding: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/icons/
    - assets/fonts/
  
  fonts:
    - family: Cabin
      fonts:
        - asset: assets/fonts/Cabin-Regular.ttf
          weight: 400
        - asset: assets/fonts/Cabin-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Cabin-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cabin-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cabin-Bold.ttf
          weight: 700

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icons/oxy-logo.png
  remove_alpha_ios: true
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: assets/icons/oxy-logo.png